spring:
  data:
    mongodb:
      host: database
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
       kafka:
         binder:
           brokers: kafka:9092
           zknodes: zookeeper:2181
       bindings:
         outputchannel:
           destination: orgchangetopic
           content-type: application/json
  cache:
    type: redis
  redis:
    url: redis://redis-cache:6379           
security:
  oauth2:
    resource:
      user-info-uri: http://authenticationservice:8091/auth/user
    client:
       client-id: ritasinc
       client-secret: passwordkey
       access-token-uri: http://authenticationservice:8091/auth/oauth/token
       user-authorization-uri: http://authenticationservice:8091/auth/oauth/authorize
  basic:
    enabled: false